
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'LogTerminal': typeof import("../components/LogTerminal.vue")['default']
    'LogViewer': typeof import("../components/LogViewer.vue")['default']
    'StatsGraph': typeof import("../components/StatsGraph.vue")['default']
    'ContainerSingle': typeof import("../components/container/Single.vue")['default']
    'UAside': typeof import("../node_modules/@nuxt/ui-pro/components/aside/Aside.vue")['default']
    'UAsideLinks': typeof import("../node_modules/@nuxt/ui-pro/components/aside/AsideLinks.vue")['default']
    'UAuthForm': typeof import("../node_modules/@nuxt/ui-pro/components/auth/AuthForm.vue")['default']
    'UBlogList': typeof import("../node_modules/@nuxt/ui-pro/components/blog/BlogList.vue")['default']
    'UBlogPost': typeof import("../node_modules/@nuxt/ui-pro/components/blog/BlogPost.vue")['default']
    'UColorModeAvatar': typeof import("../node_modules/@nuxt/ui-pro/components/color-mode/ColorModeAvatar.vue")['default']
    'UColorModeButton': typeof import("../node_modules/@nuxt/ui-pro/components/color-mode/ColorModeButton.vue")['default']
    'UColorModeImage': typeof import("../node_modules/@nuxt/ui-pro/components/color-mode/ColorModeImage.vue")['default']
    'UColorModeSelect': typeof import("../node_modules/@nuxt/ui-pro/components/color-mode/ColorModeSelect.vue")['default']
    'UColorModeToggle': typeof import("../node_modules/@nuxt/ui-pro/components/color-mode/ColorModeToggle.vue")['default']
    'UDashboardCard': typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardCard.vue")['default']
    'UDashboardLayout': typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardLayout.vue")['default']
    'UDashboardModal': typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardModal.vue")['default']
    'UDashboardNavbar': typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardNavbar.vue")['default']
    'UDashboardNavbarToggle': typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardNavbarToggle.vue")['default']
    'UDashboardPage': typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardPage.vue")['default']
    'UDashboardPanel': typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardPanel.vue")['default']
    'UDashboardPanelContent': typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardPanelContent.vue")['default']
    'UDashboardPanelHandle': typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardPanelHandle.vue")['default']
    'UDashboardSearch': typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardSearch.vue")['default']
    'UDashboardSearchButton': typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardSearchButton.vue")['default']
    'UDashboardSection': typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardSection.vue")['default']
    'UDashboardSidebar': typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardSidebar.vue")['default']
    'UDashboardSidebarLinks': typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardSidebarLinks.vue")['default']
    'UDashboardSlideover': typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardSlideover.vue")['default']
    'UDashboardToolbar': typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardToolbar.vue")['default']
    'UFooter': typeof import("../node_modules/@nuxt/ui-pro/components/footer/Footer.vue")['default']
    'UFooterColumns': typeof import("../node_modules/@nuxt/ui-pro/components/footer/FooterColumns.vue")['default']
    'UFooterLinks': typeof import("../node_modules/@nuxt/ui-pro/components/footer/FooterLinks.vue")['default']
    'UHeader': typeof import("../node_modules/@nuxt/ui-pro/components/header/Header.vue")['default']
    'UHeaderLinks': typeof import("../node_modules/@nuxt/ui-pro/components/header/HeaderLinks.vue")['default']
    'UHeaderPopoverLinks': typeof import("../node_modules/@nuxt/ui-pro/components/header/HeaderPopoverLinks.vue")['default']
    'ULandingCTA': typeof import("../node_modules/@nuxt/ui-pro/components/landing/LandingCTA.vue")['default']
    'ULandingCard': typeof import("../node_modules/@nuxt/ui-pro/components/landing/LandingCard.vue")['default']
    'ULandingFAQ': typeof import("../node_modules/@nuxt/ui-pro/components/landing/LandingFAQ.vue")['default']
    'ULandingGrid': typeof import("../node_modules/@nuxt/ui-pro/components/landing/LandingGrid.vue")['default']
    'ULandingHero': typeof import("../node_modules/@nuxt/ui-pro/components/landing/LandingHero.vue")['default']
    'ULandingLogos': typeof import("../node_modules/@nuxt/ui-pro/components/landing/LandingLogos.vue")['default']
    'ULandingSection': typeof import("../node_modules/@nuxt/ui-pro/components/landing/LandingSection.vue")['default']
    'ULandingTestimonial': typeof import("../node_modules/@nuxt/ui-pro/components/landing/LandingTestimonial.vue")['default']
    'UMain': typeof import("../node_modules/@nuxt/ui-pro/components/main/Main.vue")['default']
    'UNavigationAccordion': typeof import("../node_modules/@nuxt/ui-pro/components/navigation/NavigationAccordion.vue")['default']
    'UNavigationLinks': typeof import("../node_modules/@nuxt/ui-pro/components/navigation/NavigationLinks.vue")['default']
    'UNavigationTree': typeof import("../node_modules/@nuxt/ui-pro/components/navigation/NavigationTree.vue")['default']
    'UPage': typeof import("../node_modules/@nuxt/ui-pro/components/page/Page.vue")['default']
    'UPageBody': typeof import("../node_modules/@nuxt/ui-pro/components/page/PageBody.vue")['default']
    'UPageCard': typeof import("../node_modules/@nuxt/ui-pro/components/page/PageCard.vue")['default']
    'UPageColumns': typeof import("../node_modules/@nuxt/ui-pro/components/page/PageColumns.vue")['default']
    'UPageError': typeof import("../node_modules/@nuxt/ui-pro/components/page/PageError.vue")['default']
    'UPageGrid': typeof import("../node_modules/@nuxt/ui-pro/components/page/PageGrid.vue")['default']
    'UPageHeader': typeof import("../node_modules/@nuxt/ui-pro/components/page/PageHeader.vue")['default']
    'UPageHero': typeof import("../node_modules/@nuxt/ui-pro/components/page/PageHero.vue")['default']
    'UPageLinks': typeof import("../node_modules/@nuxt/ui-pro/components/page/PageLinks.vue")['default']
    'UPricingCard': typeof import("../node_modules/@nuxt/ui-pro/components/pricing/PricingCard.vue")['default']
    'UPricingGrid': typeof import("../node_modules/@nuxt/ui-pro/components/pricing/PricingGrid.vue")['default']
    'UPricingToggle': typeof import("../node_modules/@nuxt/ui-pro/components/pricing/PricingToggle.vue")['default']
    'UAccordion': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Accordion.vue")['default']
    'UAlert': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Alert.vue")['default']
    'UAvatar': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Avatar.vue")['default']
    'UAvatarGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/AvatarGroup")['default']
    'UBadge': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Badge.vue")['default']
    'UButton': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Button.vue")['default']
    'UButtonGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/ButtonGroup")['default']
    'UCarousel': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Carousel.vue")['default']
    'UChip': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Chip.vue")['default']
    'UDropdown': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Dropdown.vue")['default']
    'UIcon': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Icon.vue")['default']
    'UKbd': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Kbd.vue")['default']
    'ULink': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Link.vue")['default']
    'UMeter': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Meter.vue")['default']
    'UMeterGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/MeterGroup")['default']
    'UProgress': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Progress.vue")['default']
    'UCheckbox': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Checkbox.vue")['default']
    'UForm': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Form.vue")['default']
    'UFormGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/FormGroup.vue")['default']
    'UInput': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Input.vue")['default']
    'UInputMenu': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/InputMenu.vue")['default']
    'URadio': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Radio.vue")['default']
    'URadioGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/RadioGroup.vue")['default']
    'URange': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Range.vue")['default']
    'USelect': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Select.vue")['default']
    'USelectMenu': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/SelectMenu.vue")['default']
    'UTextarea': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Textarea.vue")['default']
    'UToggle': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Toggle.vue")['default']
    'UTable': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/data/Table.vue")['default']
    'UCard': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Card.vue")['default']
    'UContainer': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Container.vue")['default']
    'UDivider': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Divider.vue")['default']
    'USkeleton': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Skeleton.vue")['default']
    'UBreadcrumb': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Breadcrumb.vue")['default']
    'UCommandPalette': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPalette.vue")['default']
    'UCommandPaletteGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPaletteGroup.vue")['default']
    'UHorizontalNavigation': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/HorizontalNavigation.vue")['default']
    'UPagination': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Pagination.vue")['default']
    'UTabs': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Tabs.vue")['default']
    'UVerticalNavigation': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/VerticalNavigation.vue")['default']
    'UContextMenu': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/ContextMenu.vue")['default']
    'UModal': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modal.vue")['default']
    'UModals': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modals.client.vue")['default']
    'UNotification': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notification.vue")['default']
    'UNotifications': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notifications.vue")['default']
    'UPopover': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Popover.vue")['default']
    'USlideover': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideover.vue")['default']
    'USlideovers': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideovers.client.vue")['default']
    'UTooltip': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Tooltip.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'Icon': typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'IconCSS': typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'ColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'UModals': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
    'USlideovers': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyLogTerminal': typeof import("../components/LogTerminal.vue")['default']
    'LazyLogViewer': typeof import("../components/LogViewer.vue")['default']
    'LazyStatsGraph': typeof import("../components/StatsGraph.vue")['default']
    'LazyContainerSingle': typeof import("../components/container/Single.vue")['default']
    'LazyUAside': typeof import("../node_modules/@nuxt/ui-pro/components/aside/Aside.vue")['default']
    'LazyUAsideLinks': typeof import("../node_modules/@nuxt/ui-pro/components/aside/AsideLinks.vue")['default']
    'LazyUAuthForm': typeof import("../node_modules/@nuxt/ui-pro/components/auth/AuthForm.vue")['default']
    'LazyUBlogList': typeof import("../node_modules/@nuxt/ui-pro/components/blog/BlogList.vue")['default']
    'LazyUBlogPost': typeof import("../node_modules/@nuxt/ui-pro/components/blog/BlogPost.vue")['default']
    'LazyUColorModeAvatar': typeof import("../node_modules/@nuxt/ui-pro/components/color-mode/ColorModeAvatar.vue")['default']
    'LazyUColorModeButton': typeof import("../node_modules/@nuxt/ui-pro/components/color-mode/ColorModeButton.vue")['default']
    'LazyUColorModeImage': typeof import("../node_modules/@nuxt/ui-pro/components/color-mode/ColorModeImage.vue")['default']
    'LazyUColorModeSelect': typeof import("../node_modules/@nuxt/ui-pro/components/color-mode/ColorModeSelect.vue")['default']
    'LazyUColorModeToggle': typeof import("../node_modules/@nuxt/ui-pro/components/color-mode/ColorModeToggle.vue")['default']
    'LazyUDashboardCard': typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardCard.vue")['default']
    'LazyUDashboardLayout': typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardLayout.vue")['default']
    'LazyUDashboardModal': typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardModal.vue")['default']
    'LazyUDashboardNavbar': typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardNavbar.vue")['default']
    'LazyUDashboardNavbarToggle': typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardNavbarToggle.vue")['default']
    'LazyUDashboardPage': typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardPage.vue")['default']
    'LazyUDashboardPanel': typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardPanel.vue")['default']
    'LazyUDashboardPanelContent': typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardPanelContent.vue")['default']
    'LazyUDashboardPanelHandle': typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardPanelHandle.vue")['default']
    'LazyUDashboardSearch': typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardSearch.vue")['default']
    'LazyUDashboardSearchButton': typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardSearchButton.vue")['default']
    'LazyUDashboardSection': typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardSection.vue")['default']
    'LazyUDashboardSidebar': typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardSidebar.vue")['default']
    'LazyUDashboardSidebarLinks': typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardSidebarLinks.vue")['default']
    'LazyUDashboardSlideover': typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardSlideover.vue")['default']
    'LazyUDashboardToolbar': typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardToolbar.vue")['default']
    'LazyUFooter': typeof import("../node_modules/@nuxt/ui-pro/components/footer/Footer.vue")['default']
    'LazyUFooterColumns': typeof import("../node_modules/@nuxt/ui-pro/components/footer/FooterColumns.vue")['default']
    'LazyUFooterLinks': typeof import("../node_modules/@nuxt/ui-pro/components/footer/FooterLinks.vue")['default']
    'LazyUHeader': typeof import("../node_modules/@nuxt/ui-pro/components/header/Header.vue")['default']
    'LazyUHeaderLinks': typeof import("../node_modules/@nuxt/ui-pro/components/header/HeaderLinks.vue")['default']
    'LazyUHeaderPopoverLinks': typeof import("../node_modules/@nuxt/ui-pro/components/header/HeaderPopoverLinks.vue")['default']
    'LazyULandingCTA': typeof import("../node_modules/@nuxt/ui-pro/components/landing/LandingCTA.vue")['default']
    'LazyULandingCard': typeof import("../node_modules/@nuxt/ui-pro/components/landing/LandingCard.vue")['default']
    'LazyULandingFAQ': typeof import("../node_modules/@nuxt/ui-pro/components/landing/LandingFAQ.vue")['default']
    'LazyULandingGrid': typeof import("../node_modules/@nuxt/ui-pro/components/landing/LandingGrid.vue")['default']
    'LazyULandingHero': typeof import("../node_modules/@nuxt/ui-pro/components/landing/LandingHero.vue")['default']
    'LazyULandingLogos': typeof import("../node_modules/@nuxt/ui-pro/components/landing/LandingLogos.vue")['default']
    'LazyULandingSection': typeof import("../node_modules/@nuxt/ui-pro/components/landing/LandingSection.vue")['default']
    'LazyULandingTestimonial': typeof import("../node_modules/@nuxt/ui-pro/components/landing/LandingTestimonial.vue")['default']
    'LazyUMain': typeof import("../node_modules/@nuxt/ui-pro/components/main/Main.vue")['default']
    'LazyUNavigationAccordion': typeof import("../node_modules/@nuxt/ui-pro/components/navigation/NavigationAccordion.vue")['default']
    'LazyUNavigationLinks': typeof import("../node_modules/@nuxt/ui-pro/components/navigation/NavigationLinks.vue")['default']
    'LazyUNavigationTree': typeof import("../node_modules/@nuxt/ui-pro/components/navigation/NavigationTree.vue")['default']
    'LazyUPage': typeof import("../node_modules/@nuxt/ui-pro/components/page/Page.vue")['default']
    'LazyUPageBody': typeof import("../node_modules/@nuxt/ui-pro/components/page/PageBody.vue")['default']
    'LazyUPageCard': typeof import("../node_modules/@nuxt/ui-pro/components/page/PageCard.vue")['default']
    'LazyUPageColumns': typeof import("../node_modules/@nuxt/ui-pro/components/page/PageColumns.vue")['default']
    'LazyUPageError': typeof import("../node_modules/@nuxt/ui-pro/components/page/PageError.vue")['default']
    'LazyUPageGrid': typeof import("../node_modules/@nuxt/ui-pro/components/page/PageGrid.vue")['default']
    'LazyUPageHeader': typeof import("../node_modules/@nuxt/ui-pro/components/page/PageHeader.vue")['default']
    'LazyUPageHero': typeof import("../node_modules/@nuxt/ui-pro/components/page/PageHero.vue")['default']
    'LazyUPageLinks': typeof import("../node_modules/@nuxt/ui-pro/components/page/PageLinks.vue")['default']
    'LazyUPricingCard': typeof import("../node_modules/@nuxt/ui-pro/components/pricing/PricingCard.vue")['default']
    'LazyUPricingGrid': typeof import("../node_modules/@nuxt/ui-pro/components/pricing/PricingGrid.vue")['default']
    'LazyUPricingToggle': typeof import("../node_modules/@nuxt/ui-pro/components/pricing/PricingToggle.vue")['default']
    'LazyUAccordion': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Accordion.vue")['default']
    'LazyUAlert': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Alert.vue")['default']
    'LazyUAvatar': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Avatar.vue")['default']
    'LazyUAvatarGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/AvatarGroup")['default']
    'LazyUBadge': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Badge.vue")['default']
    'LazyUButton': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Button.vue")['default']
    'LazyUButtonGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/ButtonGroup")['default']
    'LazyUCarousel': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Carousel.vue")['default']
    'LazyUChip': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Chip.vue")['default']
    'LazyUDropdown': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Dropdown.vue")['default']
    'LazyUIcon': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Icon.vue")['default']
    'LazyUKbd': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Kbd.vue")['default']
    'LazyULink': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Link.vue")['default']
    'LazyUMeter': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Meter.vue")['default']
    'LazyUMeterGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/MeterGroup")['default']
    'LazyUProgress': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Progress.vue")['default']
    'LazyUCheckbox': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Checkbox.vue")['default']
    'LazyUForm': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Form.vue")['default']
    'LazyUFormGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/FormGroup.vue")['default']
    'LazyUInput': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Input.vue")['default']
    'LazyUInputMenu': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/InputMenu.vue")['default']
    'LazyURadio': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Radio.vue")['default']
    'LazyURadioGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/RadioGroup.vue")['default']
    'LazyURange': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Range.vue")['default']
    'LazyUSelect': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Select.vue")['default']
    'LazyUSelectMenu': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/SelectMenu.vue")['default']
    'LazyUTextarea': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Textarea.vue")['default']
    'LazyUToggle': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Toggle.vue")['default']
    'LazyUTable': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/data/Table.vue")['default']
    'LazyUCard': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Card.vue")['default']
    'LazyUContainer': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Container.vue")['default']
    'LazyUDivider': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Divider.vue")['default']
    'LazyUSkeleton': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Skeleton.vue")['default']
    'LazyUBreadcrumb': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Breadcrumb.vue")['default']
    'LazyUCommandPalette': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPalette.vue")['default']
    'LazyUCommandPaletteGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPaletteGroup.vue")['default']
    'LazyUHorizontalNavigation': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/HorizontalNavigation.vue")['default']
    'LazyUPagination': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Pagination.vue")['default']
    'LazyUTabs': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Tabs.vue")['default']
    'LazyUVerticalNavigation': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/VerticalNavigation.vue")['default']
    'LazyUContextMenu': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/ContextMenu.vue")['default']
    'LazyUModal': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modal.vue")['default']
    'LazyUModals': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modals.client.vue")['default']
    'LazyUNotification': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notification.vue")['default']
    'LazyUNotifications': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notifications.vue")['default']
    'LazyUPopover': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Popover.vue")['default']
    'LazyUSlideover': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideover.vue")['default']
    'LazyUSlideovers': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideovers.client.vue")['default']
    'LazyUTooltip': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Tooltip.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyIcon': typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'LazyIconCSS': typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'LazyColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyUModals': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
    'LazyUSlideovers': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const LogTerminal: typeof import("../components/LogTerminal.vue")['default']
export const LogViewer: typeof import("../components/LogViewer.vue")['default']
export const StatsGraph: typeof import("../components/StatsGraph.vue")['default']
export const ContainerSingle: typeof import("../components/container/Single.vue")['default']
export const UAside: typeof import("../node_modules/@nuxt/ui-pro/components/aside/Aside.vue")['default']
export const UAsideLinks: typeof import("../node_modules/@nuxt/ui-pro/components/aside/AsideLinks.vue")['default']
export const UAuthForm: typeof import("../node_modules/@nuxt/ui-pro/components/auth/AuthForm.vue")['default']
export const UBlogList: typeof import("../node_modules/@nuxt/ui-pro/components/blog/BlogList.vue")['default']
export const UBlogPost: typeof import("../node_modules/@nuxt/ui-pro/components/blog/BlogPost.vue")['default']
export const UColorModeAvatar: typeof import("../node_modules/@nuxt/ui-pro/components/color-mode/ColorModeAvatar.vue")['default']
export const UColorModeButton: typeof import("../node_modules/@nuxt/ui-pro/components/color-mode/ColorModeButton.vue")['default']
export const UColorModeImage: typeof import("../node_modules/@nuxt/ui-pro/components/color-mode/ColorModeImage.vue")['default']
export const UColorModeSelect: typeof import("../node_modules/@nuxt/ui-pro/components/color-mode/ColorModeSelect.vue")['default']
export const UColorModeToggle: typeof import("../node_modules/@nuxt/ui-pro/components/color-mode/ColorModeToggle.vue")['default']
export const UDashboardCard: typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardCard.vue")['default']
export const UDashboardLayout: typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardLayout.vue")['default']
export const UDashboardModal: typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardModal.vue")['default']
export const UDashboardNavbar: typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardNavbar.vue")['default']
export const UDashboardNavbarToggle: typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardNavbarToggle.vue")['default']
export const UDashboardPage: typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardPage.vue")['default']
export const UDashboardPanel: typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardPanel.vue")['default']
export const UDashboardPanelContent: typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardPanelContent.vue")['default']
export const UDashboardPanelHandle: typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardPanelHandle.vue")['default']
export const UDashboardSearch: typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardSearch.vue")['default']
export const UDashboardSearchButton: typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardSearchButton.vue")['default']
export const UDashboardSection: typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardSection.vue")['default']
export const UDashboardSidebar: typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardSidebar.vue")['default']
export const UDashboardSidebarLinks: typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardSidebarLinks.vue")['default']
export const UDashboardSlideover: typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardSlideover.vue")['default']
export const UDashboardToolbar: typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardToolbar.vue")['default']
export const UFooter: typeof import("../node_modules/@nuxt/ui-pro/components/footer/Footer.vue")['default']
export const UFooterColumns: typeof import("../node_modules/@nuxt/ui-pro/components/footer/FooterColumns.vue")['default']
export const UFooterLinks: typeof import("../node_modules/@nuxt/ui-pro/components/footer/FooterLinks.vue")['default']
export const UHeader: typeof import("../node_modules/@nuxt/ui-pro/components/header/Header.vue")['default']
export const UHeaderLinks: typeof import("../node_modules/@nuxt/ui-pro/components/header/HeaderLinks.vue")['default']
export const UHeaderPopoverLinks: typeof import("../node_modules/@nuxt/ui-pro/components/header/HeaderPopoverLinks.vue")['default']
export const ULandingCTA: typeof import("../node_modules/@nuxt/ui-pro/components/landing/LandingCTA.vue")['default']
export const ULandingCard: typeof import("../node_modules/@nuxt/ui-pro/components/landing/LandingCard.vue")['default']
export const ULandingFAQ: typeof import("../node_modules/@nuxt/ui-pro/components/landing/LandingFAQ.vue")['default']
export const ULandingGrid: typeof import("../node_modules/@nuxt/ui-pro/components/landing/LandingGrid.vue")['default']
export const ULandingHero: typeof import("../node_modules/@nuxt/ui-pro/components/landing/LandingHero.vue")['default']
export const ULandingLogos: typeof import("../node_modules/@nuxt/ui-pro/components/landing/LandingLogos.vue")['default']
export const ULandingSection: typeof import("../node_modules/@nuxt/ui-pro/components/landing/LandingSection.vue")['default']
export const ULandingTestimonial: typeof import("../node_modules/@nuxt/ui-pro/components/landing/LandingTestimonial.vue")['default']
export const UMain: typeof import("../node_modules/@nuxt/ui-pro/components/main/Main.vue")['default']
export const UNavigationAccordion: typeof import("../node_modules/@nuxt/ui-pro/components/navigation/NavigationAccordion.vue")['default']
export const UNavigationLinks: typeof import("../node_modules/@nuxt/ui-pro/components/navigation/NavigationLinks.vue")['default']
export const UNavigationTree: typeof import("../node_modules/@nuxt/ui-pro/components/navigation/NavigationTree.vue")['default']
export const UPage: typeof import("../node_modules/@nuxt/ui-pro/components/page/Page.vue")['default']
export const UPageBody: typeof import("../node_modules/@nuxt/ui-pro/components/page/PageBody.vue")['default']
export const UPageCard: typeof import("../node_modules/@nuxt/ui-pro/components/page/PageCard.vue")['default']
export const UPageColumns: typeof import("../node_modules/@nuxt/ui-pro/components/page/PageColumns.vue")['default']
export const UPageError: typeof import("../node_modules/@nuxt/ui-pro/components/page/PageError.vue")['default']
export const UPageGrid: typeof import("../node_modules/@nuxt/ui-pro/components/page/PageGrid.vue")['default']
export const UPageHeader: typeof import("../node_modules/@nuxt/ui-pro/components/page/PageHeader.vue")['default']
export const UPageHero: typeof import("../node_modules/@nuxt/ui-pro/components/page/PageHero.vue")['default']
export const UPageLinks: typeof import("../node_modules/@nuxt/ui-pro/components/page/PageLinks.vue")['default']
export const UPricingCard: typeof import("../node_modules/@nuxt/ui-pro/components/pricing/PricingCard.vue")['default']
export const UPricingGrid: typeof import("../node_modules/@nuxt/ui-pro/components/pricing/PricingGrid.vue")['default']
export const UPricingToggle: typeof import("../node_modules/@nuxt/ui-pro/components/pricing/PricingToggle.vue")['default']
export const UAccordion: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Accordion.vue")['default']
export const UAlert: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Alert.vue")['default']
export const UAvatar: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Avatar.vue")['default']
export const UAvatarGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/AvatarGroup")['default']
export const UBadge: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Badge.vue")['default']
export const UButton: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Button.vue")['default']
export const UButtonGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/ButtonGroup")['default']
export const UCarousel: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Carousel.vue")['default']
export const UChip: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Chip.vue")['default']
export const UDropdown: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Dropdown.vue")['default']
export const UIcon: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Icon.vue")['default']
export const UKbd: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Kbd.vue")['default']
export const ULink: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Link.vue")['default']
export const UMeter: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Meter.vue")['default']
export const UMeterGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/MeterGroup")['default']
export const UProgress: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Progress.vue")['default']
export const UCheckbox: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Checkbox.vue")['default']
export const UForm: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Form.vue")['default']
export const UFormGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/FormGroup.vue")['default']
export const UInput: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Input.vue")['default']
export const UInputMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/InputMenu.vue")['default']
export const URadio: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Radio.vue")['default']
export const URadioGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/RadioGroup.vue")['default']
export const URange: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Range.vue")['default']
export const USelect: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Select.vue")['default']
export const USelectMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/SelectMenu.vue")['default']
export const UTextarea: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Textarea.vue")['default']
export const UToggle: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Toggle.vue")['default']
export const UTable: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/data/Table.vue")['default']
export const UCard: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Card.vue")['default']
export const UContainer: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Container.vue")['default']
export const UDivider: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Divider.vue")['default']
export const USkeleton: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Skeleton.vue")['default']
export const UBreadcrumb: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Breadcrumb.vue")['default']
export const UCommandPalette: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPalette.vue")['default']
export const UCommandPaletteGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPaletteGroup.vue")['default']
export const UHorizontalNavigation: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/HorizontalNavigation.vue")['default']
export const UPagination: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Pagination.vue")['default']
export const UTabs: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Tabs.vue")['default']
export const UVerticalNavigation: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/VerticalNavigation.vue")['default']
export const UContextMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/ContextMenu.vue")['default']
export const UModal: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modal.vue")['default']
export const UModals: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modals.client.vue")['default']
export const UNotification: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notification.vue")['default']
export const UNotifications: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notifications.vue")['default']
export const UPopover: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Popover.vue")['default']
export const USlideover: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideover.vue")['default']
export const USlideovers: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideovers.client.vue")['default']
export const UTooltip: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Tooltip.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const Icon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const IconCSS: typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const ColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const UModals: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const USlideovers: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyLogTerminal: typeof import("../components/LogTerminal.vue")['default']
export const LazyLogViewer: typeof import("../components/LogViewer.vue")['default']
export const LazyStatsGraph: typeof import("../components/StatsGraph.vue")['default']
export const LazyContainerSingle: typeof import("../components/container/Single.vue")['default']
export const LazyUAside: typeof import("../node_modules/@nuxt/ui-pro/components/aside/Aside.vue")['default']
export const LazyUAsideLinks: typeof import("../node_modules/@nuxt/ui-pro/components/aside/AsideLinks.vue")['default']
export const LazyUAuthForm: typeof import("../node_modules/@nuxt/ui-pro/components/auth/AuthForm.vue")['default']
export const LazyUBlogList: typeof import("../node_modules/@nuxt/ui-pro/components/blog/BlogList.vue")['default']
export const LazyUBlogPost: typeof import("../node_modules/@nuxt/ui-pro/components/blog/BlogPost.vue")['default']
export const LazyUColorModeAvatar: typeof import("../node_modules/@nuxt/ui-pro/components/color-mode/ColorModeAvatar.vue")['default']
export const LazyUColorModeButton: typeof import("../node_modules/@nuxt/ui-pro/components/color-mode/ColorModeButton.vue")['default']
export const LazyUColorModeImage: typeof import("../node_modules/@nuxt/ui-pro/components/color-mode/ColorModeImage.vue")['default']
export const LazyUColorModeSelect: typeof import("../node_modules/@nuxt/ui-pro/components/color-mode/ColorModeSelect.vue")['default']
export const LazyUColorModeToggle: typeof import("../node_modules/@nuxt/ui-pro/components/color-mode/ColorModeToggle.vue")['default']
export const LazyUDashboardCard: typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardCard.vue")['default']
export const LazyUDashboardLayout: typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardLayout.vue")['default']
export const LazyUDashboardModal: typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardModal.vue")['default']
export const LazyUDashboardNavbar: typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardNavbar.vue")['default']
export const LazyUDashboardNavbarToggle: typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardNavbarToggle.vue")['default']
export const LazyUDashboardPage: typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardPage.vue")['default']
export const LazyUDashboardPanel: typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardPanel.vue")['default']
export const LazyUDashboardPanelContent: typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardPanelContent.vue")['default']
export const LazyUDashboardPanelHandle: typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardPanelHandle.vue")['default']
export const LazyUDashboardSearch: typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardSearch.vue")['default']
export const LazyUDashboardSearchButton: typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardSearchButton.vue")['default']
export const LazyUDashboardSection: typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardSection.vue")['default']
export const LazyUDashboardSidebar: typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardSidebar.vue")['default']
export const LazyUDashboardSidebarLinks: typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardSidebarLinks.vue")['default']
export const LazyUDashboardSlideover: typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardSlideover.vue")['default']
export const LazyUDashboardToolbar: typeof import("../node_modules/@nuxt/ui-pro/components/dashboard/DashboardToolbar.vue")['default']
export const LazyUFooter: typeof import("../node_modules/@nuxt/ui-pro/components/footer/Footer.vue")['default']
export const LazyUFooterColumns: typeof import("../node_modules/@nuxt/ui-pro/components/footer/FooterColumns.vue")['default']
export const LazyUFooterLinks: typeof import("../node_modules/@nuxt/ui-pro/components/footer/FooterLinks.vue")['default']
export const LazyUHeader: typeof import("../node_modules/@nuxt/ui-pro/components/header/Header.vue")['default']
export const LazyUHeaderLinks: typeof import("../node_modules/@nuxt/ui-pro/components/header/HeaderLinks.vue")['default']
export const LazyUHeaderPopoverLinks: typeof import("../node_modules/@nuxt/ui-pro/components/header/HeaderPopoverLinks.vue")['default']
export const LazyULandingCTA: typeof import("../node_modules/@nuxt/ui-pro/components/landing/LandingCTA.vue")['default']
export const LazyULandingCard: typeof import("../node_modules/@nuxt/ui-pro/components/landing/LandingCard.vue")['default']
export const LazyULandingFAQ: typeof import("../node_modules/@nuxt/ui-pro/components/landing/LandingFAQ.vue")['default']
export const LazyULandingGrid: typeof import("../node_modules/@nuxt/ui-pro/components/landing/LandingGrid.vue")['default']
export const LazyULandingHero: typeof import("../node_modules/@nuxt/ui-pro/components/landing/LandingHero.vue")['default']
export const LazyULandingLogos: typeof import("../node_modules/@nuxt/ui-pro/components/landing/LandingLogos.vue")['default']
export const LazyULandingSection: typeof import("../node_modules/@nuxt/ui-pro/components/landing/LandingSection.vue")['default']
export const LazyULandingTestimonial: typeof import("../node_modules/@nuxt/ui-pro/components/landing/LandingTestimonial.vue")['default']
export const LazyUMain: typeof import("../node_modules/@nuxt/ui-pro/components/main/Main.vue")['default']
export const LazyUNavigationAccordion: typeof import("../node_modules/@nuxt/ui-pro/components/navigation/NavigationAccordion.vue")['default']
export const LazyUNavigationLinks: typeof import("../node_modules/@nuxt/ui-pro/components/navigation/NavigationLinks.vue")['default']
export const LazyUNavigationTree: typeof import("../node_modules/@nuxt/ui-pro/components/navigation/NavigationTree.vue")['default']
export const LazyUPage: typeof import("../node_modules/@nuxt/ui-pro/components/page/Page.vue")['default']
export const LazyUPageBody: typeof import("../node_modules/@nuxt/ui-pro/components/page/PageBody.vue")['default']
export const LazyUPageCard: typeof import("../node_modules/@nuxt/ui-pro/components/page/PageCard.vue")['default']
export const LazyUPageColumns: typeof import("../node_modules/@nuxt/ui-pro/components/page/PageColumns.vue")['default']
export const LazyUPageError: typeof import("../node_modules/@nuxt/ui-pro/components/page/PageError.vue")['default']
export const LazyUPageGrid: typeof import("../node_modules/@nuxt/ui-pro/components/page/PageGrid.vue")['default']
export const LazyUPageHeader: typeof import("../node_modules/@nuxt/ui-pro/components/page/PageHeader.vue")['default']
export const LazyUPageHero: typeof import("../node_modules/@nuxt/ui-pro/components/page/PageHero.vue")['default']
export const LazyUPageLinks: typeof import("../node_modules/@nuxt/ui-pro/components/page/PageLinks.vue")['default']
export const LazyUPricingCard: typeof import("../node_modules/@nuxt/ui-pro/components/pricing/PricingCard.vue")['default']
export const LazyUPricingGrid: typeof import("../node_modules/@nuxt/ui-pro/components/pricing/PricingGrid.vue")['default']
export const LazyUPricingToggle: typeof import("../node_modules/@nuxt/ui-pro/components/pricing/PricingToggle.vue")['default']
export const LazyUAccordion: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Accordion.vue")['default']
export const LazyUAlert: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Alert.vue")['default']
export const LazyUAvatar: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Avatar.vue")['default']
export const LazyUAvatarGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/AvatarGroup")['default']
export const LazyUBadge: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Badge.vue")['default']
export const LazyUButton: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Button.vue")['default']
export const LazyUButtonGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/ButtonGroup")['default']
export const LazyUCarousel: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Carousel.vue")['default']
export const LazyUChip: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Chip.vue")['default']
export const LazyUDropdown: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Dropdown.vue")['default']
export const LazyUIcon: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Icon.vue")['default']
export const LazyUKbd: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Kbd.vue")['default']
export const LazyULink: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Link.vue")['default']
export const LazyUMeter: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Meter.vue")['default']
export const LazyUMeterGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/MeterGroup")['default']
export const LazyUProgress: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Progress.vue")['default']
export const LazyUCheckbox: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Checkbox.vue")['default']
export const LazyUForm: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Form.vue")['default']
export const LazyUFormGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/FormGroup.vue")['default']
export const LazyUInput: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Input.vue")['default']
export const LazyUInputMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/InputMenu.vue")['default']
export const LazyURadio: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Radio.vue")['default']
export const LazyURadioGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/RadioGroup.vue")['default']
export const LazyURange: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Range.vue")['default']
export const LazyUSelect: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Select.vue")['default']
export const LazyUSelectMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/SelectMenu.vue")['default']
export const LazyUTextarea: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Textarea.vue")['default']
export const LazyUToggle: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Toggle.vue")['default']
export const LazyUTable: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/data/Table.vue")['default']
export const LazyUCard: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Card.vue")['default']
export const LazyUContainer: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Container.vue")['default']
export const LazyUDivider: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Divider.vue")['default']
export const LazyUSkeleton: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Skeleton.vue")['default']
export const LazyUBreadcrumb: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Breadcrumb.vue")['default']
export const LazyUCommandPalette: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPalette.vue")['default']
export const LazyUCommandPaletteGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPaletteGroup.vue")['default']
export const LazyUHorizontalNavigation: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/HorizontalNavigation.vue")['default']
export const LazyUPagination: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Pagination.vue")['default']
export const LazyUTabs: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Tabs.vue")['default']
export const LazyUVerticalNavigation: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/VerticalNavigation.vue")['default']
export const LazyUContextMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/ContextMenu.vue")['default']
export const LazyUModal: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modal.vue")['default']
export const LazyUModals: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modals.client.vue")['default']
export const LazyUNotification: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notification.vue")['default']
export const LazyUNotifications: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notifications.vue")['default']
export const LazyUPopover: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Popover.vue")['default']
export const LazyUSlideover: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideover.vue")['default']
export const LazyUSlideovers: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideovers.client.vue")['default']
export const LazyUTooltip: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Tooltip.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyIcon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const LazyIconCSS: typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const LazyColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyUModals: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyUSlideovers: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
