# This is the template of a virtual host you would use for a dev project.
# Like in a production environment, each project has its own nginx vhost file.
# Use this template for your nginx vhosts in nginx/sites-enabled directory.
server {
    listen 80;
    root /home/dev/apps/first-php-81-app/public; # <-- replace first-php-81-app with your project directory name
    server_name first-php-81-app.test; # <-- replace first-php-81-app.test with your project custom domain name

    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    include /etc/nginx/php.conf;
}

# Node
server {
    listen 80;
    server_name my-node-app.test; # <-- replace with your custom domain for the project

    # location of your Node.js app's public files for serving static content directly through Nginx
    root /home/dev/apps/my-node-app/public;

    # index file to be served
    index index.html index.htm;

    location / {
        # First attempt to serve request as file, then as directory, then fall back to proxying
        try_files $uri $uri/ @nodejs;
    }

    # Define the proxy pass to Node.js app server
    location @nodejs {
        proxy_pass http://localhost:3000; # Assuming Node.js app is running on port 3000 replace localhost with your server IP or domain
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;

        # Adjust these headers according to your security requirements
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Optionally handle Node.js app paths where you want to serve index.html
    # for apps using HTML5 history API, uncomment the following location block
    # location /app {
    #     try_files $uri /app/index.html;
    # }
}
