networks:
  default:
    name: devner

services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit_devner
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: "Europe/Zurich"
    ports:
      - '1025:1025'
      - '8025:8025'

  gui:
    image: node:lts
    container_name: devner-gui
    environment:
      TZ: "Europe/Zurich"
    ports:
      - '3000:3000'
    volumes:
      - ./gui:/app
      - ~/.nuxtrc:/root/.nuxtrc
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    command: tail -f /dev/null
    working_dir: /app

  frankenphp:
    build:
      context: .
      dockerfile: ./services/frankenphp/Dockerfile
    container_name: frankenphp_devner
    restart: unless-stopped
    environment:
      TZ: "Europe/Zurich"
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - ./projects:/var/www/html/
      - ./gui:/var/www/html/gui
      - ./services/frankenphp/Caddyfile:/etc/caddy/Caddyfile
      - ./services/frankenphp/config/php.ini:/usr/local/etc/php/php.ini
    tty: true
    depends_on:
      - mysql_8
      - mailpit
      - gui

  node:
    build:
      context: ./services/node
      dockerfile: Dockerfile
    container_name: node_devner
    restart: unless-stopped
    environment:
      TZ: "Europe/Zurich"
    ports:
      # For local development outside of the container
      - '5173:5173'
    volumes:
      # mount your Node.js projects
      - ./projects:/home/dev/apps/
      - /etc/localtime:/etc/localtime:ro

  mysql_8:
    image: mysql:8.4
    restart: unless-stopped
    tty: true
    container_name: mysql8_devner
    platform: "linux/x86_64"
    ports:
      - '3306:3306'
    volumes:
      - ./services/mysql/scripts/create.sh:/create.sh
      - ./services/mysql/config/.my.cnf:/.my.cnf
      - mysql8_data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_USER: devner
      MYSQL_PASSWORD: devner
      MYSQL_ROOT_PASSWORD: devner
      TZ: "Europe/Zurich"

  mysql_5:
    image: mysql:5.7
    restart: unless-stopped
    tty: true
    container_name: mysql5_devner
    platform: "linux/x86_64"
    ports:
      - '3307:3306'
    volumes:
      - ./services/mysql/scripts/create.sh:/create.sh
      - ./services/mysql/config/.my.cnf:/.my.cnf
      - mysql5_data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_USER: devner
      MYSQL_PASSWORD: devner
      MYSQL_ROOT_PASSWORD: devner
      TZ: "Europe/Zurich"

  adminer:
    image: adminer:latest
    restart: unless-stopped
    container_name: adminer_devner
    ports:
      - '8080:8080'
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      ADMINER_DEFAULT_SERVER: mysql_8
      TZ: "Europe/Zurich"

volumes:
  mysql8_data:
  mysql5_data: