networks:
  default:
    name: devner

services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit_devner
    tty: true
    restart: unless-stopped
    environment:
      TZ: "Europe/Zurich"
    ports:
      - '1025:1025'
      - '8025:8025'
    extra_hosts:
      - "mailpit.localhost:127.0.0.1"

  frankenphp:
    build:
      context: .
      dockerfile: ./services/frankenphp/Dockerfile
    container_name: frankenphp_devner
    restart: unless-stopped
    environment:
      TZ: "Europe/Zurich"
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
      - '5173:5173' # Vite
      - '3000:3000' # Node.js
      - '8081:8081' # Expo - React Native
      - '4321:4321' # astro
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./projects:/var/www/html/
      - ./services/frankenphp/Caddyfile:/etc/frankenphp/Caddyfile
      - ./services/frankenphp/config/php.ini:/usr/local/etc/php/php.ini
      - ~/.nuxtrc:/.nuxtrc
      - caddy_data:/data # Persist Caddy's data (certificates)
      - caddy_config:/config # Persist Caddy's configuration
    tty: true
    depends_on:
      - mysql
      - postgres
      - mailpit

  mysql:
    image: mysql:8.4
    restart: unless-stopped
    tty: true
    container_name: mysql_devner
    platform: "linux/x86_64"
    ports:
      - '3306:3306'
    volumes:
      - ./services/mysql/scripts/create.sh:/create.sh
      - ./services/mysql/scripts/remove.sh:/remove.sh
      - ./services/mysql/scripts/check.sh:/check.sh
      - ./services/mysql/config/.my.cnf:/.my.cnf
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_USER: devner
      MYSQL_PASSWORD: devner
      MYSQL_ROOT_PASSWORD: devner
      TZ: "Europe/Zurich"

  postgres:
    image: postgis/postgis:14-3.5
    restart: unless-stopped
    tty: true
    container_name: postgres_devner
    platform: "linux/x86_64"
    ports:
      - '5432:5432'
    volumes:
      - ./services/postgres/scripts/create.sh:/create.sh
      - ./services/postgres/scripts/remove.sh:/remove.sh
      - ./services/postgres/scripts/check.sh:/check.sh
      - ./services/postgres/config/.pgpass:/.pgpass
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: devner
      POSTGRES_PASSWORD: devner
      POSTGRES_DB: devner
      PGPASSFILE: /.pgpass
      TZ: "Europe/Zurich"

  adminer:
    image: adminer:latest
    restart: unless-stopped
    container_name: adminer_devner
    tty: true
    environment:
      ADMINER_PLUGINS: "tables-filter tinymce json-column dump-zip"
      ADMINER_DEFAULT_SERVER: mysql
      TZ: "Europe/Zurich"
    extra_hosts:
      - "adminer.localhost:127.0.0.1"

  redis:
    image: redis:alpine
    container_name: redis_devner
    tty: true
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  mysql_data:
  postgres_data:
  redis_data:
  caddy_data:
  caddy_config: