// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActiveProvider() {
  return window['go']['main']['App']['ActiveProvider']();
}

export function AddHost(arg1, arg2) {
  return window['go']['main']['App']['AddHost'](arg1, arg2);
}

export function AgentChat(arg1, arg2, arg3) {
  return window['go']['main']['App']['AgentChat'](arg1, arg2, arg3);
}

export function AgentConfirm(arg1, arg2) {
  return window['go']['main']['App']['AgentConfirm'](arg1, arg2);
}

export function AgentReset(arg1) {
  return window['go']['main']['App']['AgentReset'](arg1);
}

export function CertsStatus() {
  return window['go']['main']['App']['CertsStatus']();
}

export function CreateDatabase(arg1, arg2) {
  return window['go']['main']['App']['CreateDatabase'](arg1, arg2);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DevServerStatus(arg1) {
  return window['go']['main']['App']['DevServerStatus'](arg1);
}

export function DropDatabase(arg1, arg2) {
  return window['go']['main']['App']['DropDatabase'](arg1, arg2);
}

export function GetConfigInfo() {
  return window['go']['main']['App']['GetConfigInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallCertsCA() {
  return window['go']['main']['App']['InstallCertsCA']();
}

export function ListDatabases() {
  return window['go']['main']['App']['ListDatabases']();
}

export function ListEditors() {
  return window['go']['main']['App']['ListEditors']();
}

export function ListHosts() {
  return window['go']['main']['App']['ListHosts']();
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListProviders() {
  return window['go']['main']['App']['ListProviders']();
}

export function OpenConfigFile() {
  return window['go']['main']['App']['OpenConfigFile']();
}

export function OpenInEditor(arg1, arg2) {
  return window['go']['main']['App']['OpenInEditor'](arg1, arg2);
}

export function OpenProjectURL(arg1) {
  return window['go']['main']['App']['OpenProjectURL'](arg1);
}

export function RebuildStack() {
  return window['go']['main']['App']['RebuildStack']();
}

export function RemoveHost(arg1) {
  return window['go']['main']['App']['RemoveHost'](arg1);
}

export function StackStatus() {
  return window['go']['main']['App']['StackStatus']();
}

export function StartDevServer(arg1, arg2) {
  return window['go']['main']['App']['StartDevServer'](arg1, arg2);
}

export function StartStack() {
  return window['go']['main']['App']['StartStack']();
}

export function StopDevServer(arg1) {
  return window['go']['main']['App']['StopDevServer'](arg1);
}

export function StopStack() {
  return window['go']['main']['App']['StopStack']();
}

export function TailLogs(arg1, arg2) {
  return window['go']['main']['App']['TailLogs'](arg1, arg2);
}
