// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {network} from '../models';
import {main} from '../models';
import {app} from '../models';
import {store} from '../models';

export function ActiveProvider():Promise<string>;

export function AddHost(arg1:string,arg2:string):Promise<void>;

export function AgentChat(arg1:string,arg2:string,arg3:string):Promise<string>;

export function AgentConfirm(arg1:string,arg2:boolean):Promise<void>;

export function AgentReset(arg1:string):Promise<void>;

export function CertsStatus():Promise<network.CertsStatus>;

export function CreateDatabase(arg1:string,arg2:string):Promise<main.CreateDatabaseResult>;

export function CreateProject(arg1:app.CreateProjectRequest):Promise<app.CreateProjectResult>;

export function DeleteProject(arg1:string):Promise<void>;

export function DevServerStatus(arg1:string):Promise<main.DevServerStatusDTO>;

export function DropDatabase(arg1:string,arg2:string):Promise<void>;

export function GetConfigInfo():Promise<main.ConfigInfo>;

export function Greet(arg1:string):Promise<string>;

export function InstallCertsCA():Promise<void>;

export function ListDatabases():Promise<Array<main.DatabaseInfo>>;

export function ListEditors():Promise<Array<string>>;

export function ListHosts():Promise<Array<main.HostEntryDTO>>;

export function ListProjects():Promise<Array<store.Project>>;

export function ListProviders():Promise<Array<string>>;

export function OpenConfigFile():Promise<void>;

export function OpenInEditor(arg1:string,arg2:string):Promise<void>;

export function OpenProjectURL(arg1:string):Promise<void>;

export function RebuildStack():Promise<void>;

export function RemoveHost(arg1:string):Promise<void>;

export function StackStatus():Promise<Array<main.ContainerStatus>>;

export function StartDevServer(arg1:string,arg2:string):Promise<void>;

export function StartStack():Promise<void>;

export function StopDevServer(arg1:string):Promise<void>;

export function StopStack():Promise<void>;

export function TailLogs(arg1:string,arg2:number):Promise<string>;
