map $http_host $phpfpm {
    'api.nexelar.local' 'php_8_1';
    'terrraterrre.local' 'php_8_1';
    'val-de-bagne.local' 'php_8_1';
    'nexelar.local' 'php_8_1';
    'fetedelanature.local' 'php_8_1';
    'wp.fetedelanature.local' 'php_8_1';
    'epesses.local' 'php_8_1';
    'favre-tchippis.local' 'php_8_1';
    'efk.local' 'php_8_1';
    'fete-de-la-musique.local' 'php_8_1';
    'cnvsuisse.local' 'php_8_1';

    'mrn.local' 'php_8_1';
}