// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/containers': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/containers').default>>>>
    }
    '/api/containers/:id/details': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/containers/[id]/details').default>>>>
    }
    '/api/containers/:id/exec': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/containers/[id]/exec').default>>>>
    }
    '/api/containers/:id/logs': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/containers/[id]/logs').default>>>>
    }
    '/api/containers/:id/rebuild': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/containers/[id]/rebuild').default>>>>
    }
    '/api/containers/:id/remove': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/containers/[id]/remove').default>>>>
    }
    '/api/containers/:id/restart': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/containers/[id]/restart').default>>>>
    }
    '/api/containers/:id/start': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/containers/[id]/start').default>>>>
    }
    '/api/containers/:id/stop': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/containers/[id]/stop').default>>>>
    }
    '/api/containers/create': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/containers/create').default>>>>
    }
    '/api/containers/stop': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/containers/stop').default>>>>
    }
    '/api/databases/create': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/databases/create').default>>>>
    }
    '/api/databases/delete': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/databases/delete').default>>>>
    }
    '/api/projects/:name/delete': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/[name]/delete').default>>>>
    }
    '/api/projects/create': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/create').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}