name: ci

on:
  push:
    branches: [main, v2]
  pull_request:
    branches: [main, v2]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: true
      - name: Build
        working-directory: devner-go
        run: go build ./...
      - name: Test
        working-directory: devner-go
        run: go test ./...

  vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: go vet
        working-directory: devner-go
        run: go vet ./...
